[2025-04-20T06:28:07.188+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_stg_to_dwh_to_mart.task_dwh_to_mart manual__2025-04-20T06:27:49.387672+00:00 [queued]>
[2025-04-20T06:28:07.200+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_stg_to_dwh_to_mart.task_dwh_to_mart manual__2025-04-20T06:27:49.387672+00:00 [queued]>
[2025-04-20T06:28:07.201+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-04-20T06:28:07.223+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): task_dwh_to_mart> on 2025-04-20 06:27:49.387672+00:00
[2025-04-20T06:28:07.231+0000] {standard_task_runner.py:60} INFO - Started process 272 to run task
[2025-04-20T06:28:07.236+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_stg_to_dwh_to_mart', 'task_dwh_to_mart', 'manual__2025-04-20T06:27:49.387672+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main_etl.py', '--cfg-path', '/tmp/tmp60s6oyqu']
[2025-04-20T06:28:07.240+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask task_dwh_to_mart
[2025-04-20T06:28:07.307+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_stg_to_dwh_to_mart.task_dwh_to_mart manual__2025-04-20T06:27:49.387672+00:00 [running]> on host 2bbd376576f1
[2025-04-20T06:28:07.430+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_stg_to_dwh_to_mart' AIRFLOW_CTX_TASK_ID='task_dwh_to_mart' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T06:27:49.387672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T06:27:49.387672+00:00'
[2025-04-20T06:28:07.432+0000] {dwh_to_mart.py:107} INFO - Starting ETL Process...
[2025-04-20T06:28:07.432+0000] {dwh_to_mart.py:46} INFO - Config validation passed
[2025-04-20T06:28:07.432+0000] {dwh_to_mart.py:51} INFO - Extracting data from raw.patient...
[2025-04-20T06:28:07.474+0000] {dwh_to_mart.py:62} INFO - Transforming data for dim_patient...
[2025-04-20T06:28:07.476+0000] {dwh_to_mart.py:72} INFO - Replacing data in dim_patient...
[2025-04-20T06:28:07.494+0000] {dwh_to_mart.py:100} ERROR - Error replacing data in dim_patient: 'RootTransaction' object has no attribute 'execute'
[2025-04-20T06:28:07.495+0000] {dwh_to_mart.py:115} ERROR - ETL process failed: 'RootTransaction' object has no attribute 'execute'
[2025-04-20T06:28:07.495+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-04-20T06:28:07.509+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_stg_to_dwh_to_mart, task_id=task_dwh_to_mart, execution_date=20250420T062749, start_date=20250420T062807, end_date=20250420T062807
[2025-04-20T06:28:07.569+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-20T06:28:07.629+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
